version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - gnlow
  ignore:
  - dependency-name: lodash
    versions:
    - 4.17.20
